/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automata;

import javax.swing.JOptionPane;

/**WIDTH
 *
 * @author ivankeys
 */
public class frame extends javax.swing.JFrame {
    int aceptar=0;
    int error=0;
    int cont=0; 
    
    char [] caracteres; 
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        setLocation(500,200);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCadena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Automata ");

        txtCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadenaActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese una palabra:");

        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadenaActionPerformed
        
        // TODO ad = "print"d your handling code here:
    }//GEN-LAST:event_txtCadenaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame fra= new frame(); 
            String cadena = txtCadena.getText();
             fra.caracteres=cadena.toCharArray(); /*para guardar los caratcteres y los va ir separando*/
               fra.inicio();    
               fra.verificar();
          
             
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCadena;
    // End of variables declaration//GEN-END:variables


public void inicio (){ /*metodo*/ 
         cont = 0; 
         q0();/*irnos al codigo 0 */ 
     } 
     public void q0(){ 
         System.out.println("Entro a  --> q0");/*imprimimos y decimos que estamos en q0*/ 
         if(cont < caracteres.length){/*cuantos espacios tiene mi arreglo*/ 
             if(caracteres[cont]=='+'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q1();
             }else if (caracteres[cont]=='-'){
                 cont++; 
                 q2();/*nos va a mover al estado uno*/ 
             }else if (caracteres[cont]=='='){
                 cont++; 
                 q3();/*nos va a mover al estado uno*/ 
             }else if(caracteres[cont]=='0'){
                 error=-1;
             }             
             else if(caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++;
            q4();
         }else if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'){
          cont++;
            q6();   
         }else if(caracteres[cont]=='p'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q8();
         }
        } 


     } 
     public void q1(){ 
         if(cont==caracteres.length){
           aceptar=1;
     System.out.println("estoy en q1 --> sumar"); 
         }else{
             error=-1;
         }
     } 
     public void q2(){ 
       if(cont==caracteres.length){
           aceptar=1;
     System.out.println("estoy en q2 -->restar"); 
         }else{
             error=-1;
         }        
     } 
     public void q3(){   
         if(cont==caracteres.length){
           aceptar=1;
     System.out.println("estoy en --> q3 asignar"); 
         }else{
             error=-1;
         }
    
     } 
       public void q4(){ 
     System.out.println("estoy en --> q4 "); 
    if(cont < caracteres.length){
        if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
        cont++;
        q5();  
        }
        else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++;
            q4();
         }else if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
             cont++;
             q5();
         }
        
    }   
    error=-1;
     }
        public void q5(){ 
    
  if(cont==caracteres.length){
           aceptar=1;
      System.out.println("estoy en --> q5 Entero"); 
         }else{
             error=-1;
         }
        } 
      public void q6(){ 
     System.out.println("estoy en --> q6 "); 
     if(cont < caracteres.length){
         if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
             cont++;
             q6();
         }else if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
        cont++;
        q7();  
        }else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++;
            q7();
     
       }
    
         }
     error=-1;
     }
        
      public void q7(){ 
   if(cont==caracteres.length){
           aceptar=1;
      System.out.println("estoy en --> q7 LETRAS"); 
         }else{
             error=-1;
         }    
     }
      
      
         public void q8(){ 
     System.out.println("estoy en --> q8 "); 
         if(cont < caracteres.length){
             //letras-r
             if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
                 cont++;
                 q6();
             }else if(caracteres[cont]=='r'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q9();}
             else if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
                       cont++;
                          q13();  
        }else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++;
            q13();
            }  
         }
         error=-1;
     } 
     
   public void q9(){ 
     System.out.println("estoy en --> q9"); 
    if(cont<caracteres.length){
     if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
                       cont++;
                          q13();  
        }else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++;
            q13();
            }else if(caracteres[cont]=='i'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q10();
       }else  if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
           cont++;
           q6();
       }
    } 
    error=-1;
     }
             public void q10(){ 
     System.out.println("estoy en --> q10"); 
         if(cont<caracteres.length){
           if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
                       cont++;
                          q13();  
        }else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++; 
            q13();
            }else if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='t'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
                cont++;
                q6();
            }else if(caracteres[cont]=='n'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q11();
            }
         }
         error=-1;
     }
             public void q11(){ 
     System.out.println("estoy en --> q11"); 
      if(cont<caracteres.length){
         if(caracteres[cont]=='+'||caracteres[cont]=='-'||caracteres[cont]=='='){
                       cont++;
                          q13();  
        }else if(caracteres[cont]=='0'||caracteres[cont]=='1'|| caracteres[cont]=='2'||caracteres[cont]=='3'||caracteres[cont]=='4'||caracteres[cont]=='5'||caracteres[cont]=='6'||caracteres[cont]=='7'||caracteres[cont]=='8'||caracteres[cont]=='9'){
            cont++; 
            q13();
            } else if(caracteres[cont]=='t'){/*el arreglo car en el contador 0 lo vamos a comparar si es = a*/ 
             cont++;/*incrememnto mi contador*/ 
             q12();
            }else  if(caracteres[cont]=='a'|| caracteres[cont]=='b'||caracteres[cont]=='c'||caracteres[cont]=='d'||caracteres[cont]=='e'||caracteres[cont]=='f'||caracteres[cont]=='g'||caracteres[cont]=='h'||caracteres[cont]=='i'||caracteres[cont]=='j'||caracteres[cont]=='k'||caracteres[cont]=='l'||caracteres[cont]=='m'||caracteres[cont]=='n'||caracteres[cont]=='ñ'||caracteres[cont]=='o'||caracteres[cont]=='q'||caracteres[cont]=='r'||caracteres[cont]=='s'||caracteres[cont]=='u'||caracteres[cont]=='v'||caracteres[cont]=='w'||caracteres[cont]=='x'||caracteres[cont]=='y'||caracteres[cont]=='z'||caracteres[cont]=='p'){
                cont++;
                q6();
      }
      }
      error=-1;
     }
             public void q12(){ 
               if(cont==caracteres.length){
           aceptar=1;
     System.out.println("estoy en --> q12 IMPRIMIR ");  
         }else{
             error=-1;
         } 
   
     
     }
             public void q13(){ 
    // System.out.println("En q13 letras"); 
     if(cont==caracteres.length){
           aceptar=1;
     System.out.println("estoy en --> q13 LETRAS");  
         }else{
             error=-1;
         } 
     }
            
     public void verificar(){ 
                    if(aceptar==1){
                   JOptionPane.showMessageDialog(null,"Expresion valida");
           
               }else if(error==-1){
                    JOptionPane.showMessageDialog(null,"Expresion no valida");
              
               }else{
                   JOptionPane.showMessageDialog(null,"no esta permitido");
               } 
                   
     }

}








